#cloud-config
hostname: TO_SET
manage_etc_hosts: true
timezone: Europe/Brussels
keyboard:
  model: pc105
  layout: "be"

packages:
- avahi-daemon
- apt-transport-https
- ca-certificates
- curl
- gnupg
- lsb-release
- glances
- htop
- vim

apt:
  conf: |
    Acquire {
      Check-Date "false";
    };

users:
- name: pi
  groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo,docker
  shell: /bin/bash
  lock_passwd: false
  passwd: $5$dTrrr00mCc$QXrVvRAVXFjilC.TgGQIsrLVaybCYRrllsSkiKXfT58
  ssh_authorized_keys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICF1a6Pj8MCGEGsoDx6t0IWcKbXrQ3Jr/QSRXRVk80q2 thibault@spin42.com"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgM6eTRgK/EZmcjy7OHd+/LEuLYE19/MgkiwBcmygek marc@spin42.com"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINkwfpnYKR1bnpxyNnYNZ47gUMovmTnyosRiEZMu3FRJ loic@spin42.com"
  sudo: ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/systemd/system/ovcs-ros2.service
    permissions: "0644"
    owner: pi:pi
    content: |
      [Unit]
      Description=OVCS Ros2 Docker Compose
      Requires=docker.service
      After=docker.service

      [Service]
      WorkingDirectory=/home/pi/ros2_docker
      Environment=HOME=/home/pi
      ExecStartPre=/bin/mkdir -p /home/pi/ros2_docker
      ExecStartPre=/usr/bin/git config --global --add safe.directory /home/pi/ros2_docker
      ExecStartPre=/usr/bin/git -C /home/pi/ros2_docker pull
      ExecStart=/bin/sh -c "/usr/bin/docker compose -f compose/$(hostname).yaml up --remove-orphans -d"
      ExecStop=/bin/sh -c "/usr/bin/docker compose -f compose/$(hostname).yaml stop"
      TimeoutStartSec=0
      RemainAfterExit=yes
      User=pi

      [Install]
      WantedBy=multi-user.target

runcmd:
  - until ping -c1 1.1.1.1 >/dev/null 2>&1; do echo "Waiting for internet..."; sleep 2; done
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin git
  - usermod -aG docker pi
  - systemctl enable docker
  - systemctl start docker
  - sudo su - pi -c 'git clone https://github.com/open-vehicle-control-system/ovcs_ros2 /home/pi/ovcs_ros2'
  - sudo su - pi -c 'git clone https://github.com/open-vehicle-control-system/ros2_docker /home/pi/ros2_docker'
  - docker version
  - docker compose version
  - systemctl daemon-reload
  - systemctl enable ovcs-ros2.service
  - systemctl start ovcs-ros2.service
